<?php
/**
* Copyright © Magefan (support@magefan.com). All rights reserved.
* Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
*/

    $ruleId = ($block->getData('rule_id')) ?: 'YOUR_RULE_ID';
?>

<div class="container sample">
    <span id="sample-header"><?= __('You can paste related products in next ways:'); ?></span>
    <div class="item">
       <div class="item">
           <div class="title"><?=__('Add Widget with name "Auto Related Products (Plus) Block" and select needed rule from a list')?></div>
       </div>
       <div class="item">
           <div class="title">Add as Widget in CMS block, page</div>
           <div class="description">{{widget type="Magefan\AutoRelatedProduct\Block\Widget\RelatedList" rule_id="<?= $ruleId ?>"}}</div>
       </div>
       <div class="title">Add as Block in Layout</div>
       <div class="description">
           <pre>
&lt;referenceContainer name="content"&gt;
        &lt;block class="Magefan\AutoRelatedProduct\Block\RelatedProductList"
               template="Magefan_AutoRelatedProduct::product/list/related_product_items.phtml"
               name="magefan.related-product-list"&gt;
                &lt;arguments&gt;
                    &lt;argument name="rule_id" xsi:type="string"&gt;<?= $ruleId ?>&lt;/argument&gt;
                &lt;/arguments&gt;
        &lt;/block&gt;
&lt;/referenceContainer&gt;
           </pre>
       </div>
   </div>
    <div class="item">
        <div class="title">Template file (*.phtml)</div>
        <div class="description">
                <?= htmlspecialchars('<?= $block->getLayout()->createBlock(\Magefan\AutoRelatedProduct\Block\RelatedProductList::class)->setRuleId('.$ruleId.')->toHtml();?>');?>
        </div>
    </div>
</div>

<style>
    .container.sample {
        border: 1px solid rgba(0,0,0,.125);
        width: 70%;
        margin: 0 auto;
        background: #f1f1f1;
        box-shadow: 2px 2px 8px rgb(0 0 0 / 22%);
        padding: 0px;
        margin-bottom: 40px;
    }

    .container.sample .item {
        border-bottom: 1px solid rgba(0,0,0,.125);
        padding: 10px;
    }

    .container.sample .item:last-child {border-bottom: none;}
    .container.sample .item .title {font-weight: 700; font-size: 1.6rem; padding: 10px 10px 10px 25px;}

    .container.sample #sample-header {
        background-color: #373330;
        padding: 25px;
        color: #fff;
        text-align: center;
        display: block;
    }
</style>
