<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var $block \Magefan\AutoRelatedProduct\Block\Adminhtml\CheckEnableInfo
 */
?>
<?php if (!$block->isEnabled()) { ?>
    <div class="messages">
        <div class="message message-error">
            <div data-ui-id="messages-message-error">
                <?php $html = __('Magefan Auto Related Products is disabled, to enable the extension please navigate to
                <a href="%1" target="_blank">Stores > Configuration > Magefan Extensions > Auto Related Products</a>.
                ', $block->getUrl('adminhtml/system_config/edit', ['section' => 'autorp']));
                ?>
                <?= /**@noEscape**/ $html ?>
            </div>
        </div>
    </div>
<?php } ?>

<style>
    .admin__field[data-index="apply_same_as_condition"] {
        margin-top: 40px;
    }

    #autorp_rule_formrule_same_as_conditions_fieldset_ {
        margin-left: 25%;
        margin-bottom: 60px;
    }

    #autorp_rule_formrule_actions_fieldset_,
    #autorp_rule_formrule_conditions_fieldset_,
    [data-index="preview_button"] {
        margin-left: 30px;
    }
    .hide-preview-button {
        margin-left: 20px;
    }
</style>

<?php if (!$block->isDisplayModesAvailable() && $affectedRules = $block->getAffectedRules()) { ?>
    <div class="messages">
        <div class="message message-error">
            <div data-ui-id="messages-message-error">
                <p style="font-size: 16px">
                    <?= $escaper->escapeHtml(__('Display Modes:')) ?> "From Same Category Only", "Only With Higher Price", "Only With Lower Price"
                    <?= $escaper->escapeHtml(__('are not longer available in the basic version!')) ?>
                </p>

                <p style="font-size: 16px">
                    <?= $escaper->escapeHtml(__('Please')) ?>
                    <a href="https://magefan.com/magento-2-automatic-related-products/pricing" target="_blank">
                        <?= $escaper->escapeHtml(__('upgrade')) ?>
                    </a>
                    <?= $escaper->escapeHtml(__(' to Plus or Extra version to be able to use this options.')) ?>
                </p>
                <br>
                <p style="font-size: 16px">
                    <?= $escaper->escapeHtml(__('Affected rule IDs: %1.', $affectedRules)) ?>
                </p>
            </div>
        </div>
    </div>
<?php } ?>
