<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var $block \Magefan\AutoRelatedProduct\Block\Adminhtml\CheckEnableInfo
 */
?>
<?php if (!$block->isEnabled()) { ?>
    <div class="messages">
        <div class="message message-error">
            <div data-ui-id="messages-message-error">
                <?php $html = __('Magefan Auto Related Products is disabled, to enable the extension please navigate to
                <a href="%1" target="_blank">Stores > Configuration > Magefan Extensions > Auto Related Products</a>.
                ', $block->getUrl('adminhtml/system_config/edit', ['section' => 'autorp']));
                ?>
                <?= /**@noEscape**/ $html ?>
            </div>
        </div>
    </div>
<?php } ?>

<style>
    .admin__field[data-index="apply_same_as_condition"] {
        margin-top: 40px;
    }

    #autorp_rule_formrule_same_as_conditions_fieldset_ {
        margin-left: 25%;
        margin-bottom: 60px;
    }

    #autorp_rule_formrule_actions_fieldset_,
    #autorp_rule_formrule_conditions_fieldset_,
    [data-index="preview_button"] {
        margin-left: 30px;
    }
    .hide-preview-button {
        margin-left: 20px;
    }
</style>

